CREATE TABLE SAMPLE_TABLE (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CODE VARCHAR(128),
    NAME VARCHAR(128),
    CONSTRAINT SAMPLE_TABLE_PK PRIMARY KEY (ID)
);

INSERT INTO SAMPLE_TABLE (CODE, NAME) VALUES ('FOO', 'foo');
INSERT INTO SAMPLE_TABLE (CODE, NAME) VALUES ('BAR', 'bar');
INSERT INTO SAMPLE_TABLE (CODE, NAME) VALUES ('FIZZ', 'fizz');
INSERT INTO SAMPLE_TABLE (CODE, NAME) VALUES ('BUZZ', 'buzz');
